version: '3.3'

services:
  api-docs:
    image: reach/api-docs:latest
    ports:
      - 8889:8888
    environment:
      - USERNAME=reach
      - PASSWORD=superunknown
    networks:
      - cluster_network
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=api-docs.rea.ch
        - com.df.port=8888
        - com.df.usersSecret=admin
        - com.df.reschedule=true
        - com.df.rack=tool
      placement:
        constraints:
          - node.labels.com.reach.rack == tool
        preferences:
          - spread: node.labels.com.reach.zone

networks:
  cluster_network:
    external:
      name: cluster_network
