version: '3.3'

services:
  api-docs:
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=api-docs.reach.chat
        - com.df.usersSecret=admin
        - com.df.port=8888
