version: '3.3'

services:
  api-docs:
    image: reach/api-docs:latest
    ports:
      - 8889:8888
    environment:
      - USERNAME=reach
      - PASSWORD=superunknown
    networks:
      - cluster_network
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=api-docs.rea.ch
        - com.df.port=8888
      placement:
        constraints:
          - node.role == worker

networks:
  cluster_network:
    external:
      name: cluster_network
